### ISSUE TITLE
Uncaught TypeError by processing GetVehicleData request after vehicle data remove on HMI

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_hmi#667]
#### Precondition:
1. SDL and HMI are started
2. Mobile app is registered and activated
3. Permissions for `GetVehicleData` and required data are granted

#### Steps to reproduce:
1. On HMI go to "vehicle Info" -> "Edit Vehicle Data" -> "Delete"
2. Mobile app requests GetVehicleData with allowed parameter

#### Expected result:
1. HMI responds to the `VI.GetVehicleData(<requested_vehicle_data> = { resultCode = "VEHICLE_DATA_NOT_AVAILABLE" })`
2. Mobile app gets result code received from HMI

#### Actual result:
1. HMI does not respond to the `VI.GetVehicleData` and logs error in the console 
```
Uncaught TypeError: Cannot read properties of null (reading 'bodyInformation')
    at d.getVehicleData (VehicleInfoModel.js:602:31)
    at d.onRPCRequest (VehicleInfoRPC.js:141:37)
    at d [as onRPCRequest] (ember-1.0.pre.min.js:14:5785)
    at d.onWSMessage (RPCClient.js:190:40)
    at WebSocket.socket.onmessage (RPCClient.js:81:14)
```
2. Mobile app gets "GENERIC_ERROR" result code

**Comment by GetmanetsIrina** [comment]
@theresalech, we consider the current issue as regression one, because it can be reproduced on the commit after #630 (issue from the scope for 8.1 release)

**Comment by GetmanetsIrina** [comment]
@theresalech, Luxoft team is not planning to submit a PR to resolve this issue.
